export type ColourBoardChoice = {
  id: string;
  option_group: string;
  color_name: string;
  color_hex: string;
  swatch_image_url: string;
  option_image_url: string;
  price_adjustment: string;
  default_option: boolean;
  notes: string;
  source_count: number;
};

export const COLOUR_BOARD_CHOICES = [
    {
        "id":  "black-diamond-board-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-12833-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Diamond Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/12833_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/12833_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  22
    },
    {
        "id":  "black-diamond-board-70-19-https-www-flightcasewarehouse-co-uk-content-shared-productpics-12834-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Diamond Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/12834_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/12834_0_l.jpg",
        "price_adjustment":  "70.19",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  55
    },
    {
        "id":  "black-lightweight-astroboard-17-54-https-www-flightcasewarehouse-co-uk-content-shared-productpics-7253-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Lightweight Astroboard",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7253_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7253_0_l.jpg",
        "price_adjustment":  "17.54",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "black-lightweight-astroboard-19-88-https-www-flightcasewarehouse-co-uk-content-shared-productpics-7313-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Lightweight Astroboard",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7313_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7313_0_l.jpg",
        "price_adjustment":  "19.88",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  15
    },
    {
        "id":  "black-lightweight-astroboard-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-7314-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Lightweight Astroboard",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7314_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/7314_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  29
    },
    {
        "id":  "black-lightweight-astroboard-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10057-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Lightweight Astroboard",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10057_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10057_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "black-lightweight-astroboard-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10063-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Lightweight Astroboard",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10063_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10063_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  9
    },
    {
        "id":  "black-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11428-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11428_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11428_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "black-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11429-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11429_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11429_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "black-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11430-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11430_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11430_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  26
    },
    {
        "id":  "black-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11431-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11431_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11431_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "black-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11432-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11432_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11432_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  27
    },
    {
        "id":  "black-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13794-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13794_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13794_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "black-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13798-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13798_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13798_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "black-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13797-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Black Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13797_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13797_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "blue-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11404-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11404_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11404_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "blue-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11405-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11405_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11405_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  13
    },
    {
        "id":  "blue-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11406-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11406_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11406_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  27
    },
    {
        "id":  "blue-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11407-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11407_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11407_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  13
    },
    {
        "id":  "blue-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11408-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11408_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11408_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  30
    },
    {
        "id":  "blue-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13799-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13799_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13799_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "blue-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13795-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13795_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13795_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "blue-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13796-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Blue Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13796_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13796_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  39
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11397-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11397_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11397_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11395-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11395_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11395_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11394-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11394_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11394_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  26
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11396-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11396_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11396_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11398-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11398_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11398_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  31
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13802-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13802_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13802_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13801-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13801_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13801_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "bordeaux-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13800-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Bordeaux Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13800_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13800_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "grey-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11401-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11401_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11401_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "grey-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11400-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11400_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11400_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "grey-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11399-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11399_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11399_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  26
    },
    {
        "id":  "grey-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11402-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11402_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11402_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "grey-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11403-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11403_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11403_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  31
    },
    {
        "id":  "grey-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13812-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13812_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13812_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "grey-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13811-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13811_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13811_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "grey-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13810-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Grey Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13810_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13810_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11409-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11409_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11409_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  10
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11410-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11410_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11410_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11411-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11411_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11411_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  24
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11412-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11412_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11412_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  13
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11505-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11505_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11505_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  35
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13815-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13815_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13815_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13814-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13814_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13814_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  19
    },
    {
        "id":  "mint-green-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13813-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Mint Green Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13813_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13813_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  35
    },
    {
        "id":  "none-https-www-flightcasewarehouse-co-uk-content-layout-coloured-board-none-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "None",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/layout/coloured-board-none.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/layout/coloured-board-none.jpg",
        "price_adjustment":  "",
        "default_option":  true,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  157
    },
    {
        "id":  "orange-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11418-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11418_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11418_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  10
    },
    {
        "id":  "orange-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11419-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11419_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11419_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  13
    },
    {
        "id":  "orange-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11420-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11420_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11420_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  26
    },
    {
        "id":  "orange-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11421-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11421_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11421_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "orange-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11422-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11422_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11422_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  31
    },
    {
        "id":  "orange-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13818-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13818_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13818_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "orange-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13817-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13817_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13817_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "orange-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13816-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Orange Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13816_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13816_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "pink-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11379-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11379_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11379_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "pink-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11380-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11380_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11380_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "pink-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11381-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11381_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11381_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  24
    },
    {
        "id":  "pink-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11382-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11382_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11382_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "pink-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11383-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11383_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11383_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  31
    },
    {
        "id":  "pink-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13821-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13821_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13821_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "pink-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13820-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13820_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13820_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "pink-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13819-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Pink Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13819_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13819_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "purple-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11384-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11384_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11384_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "purple-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11385-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11385_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11385_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "purple-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11386-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11386_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11386_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  24
    },
    {
        "id":  "purple-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11387-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11387_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11387_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "purple-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11388-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11388_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11388_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  32
    },
    {
        "id":  "purple-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13824-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13824_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13824_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "purple-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13823-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13823_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13823_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "purple-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13822-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Purple Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13822_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13822_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "red-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11423-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11423_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11423_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  10
    },
    {
        "id":  "red-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11424-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11424_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11424_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "red-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11425-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11425_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11425_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  24
    },
    {
        "id":  "red-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11426-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11426_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11426_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "red-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11427-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11427_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11427_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  29
    },
    {
        "id":  "red-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13827-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13827_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13827_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "red-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13826-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13826_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13826_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  17
    },
    {
        "id":  "red-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13825-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Red Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13825_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13825_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  40
    },
    {
        "id":  "stucco-aluminium-board-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10050-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Stucco Aluminium Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10050_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10050_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  7
    },
    {
        "id":  "stucco-aluminium-board-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10054-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Stucco Aluminium Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10054_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10054_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  15
    },
    {
        "id":  "stucco-aluminium-board-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10056-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Stucco Aluminium Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10056_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10056_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  35
    },
    {
        "id":  "stucco-aluminium-board-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10061-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Stucco Aluminium Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10061_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10061_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "stucco-aluminium-board-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-10068-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Stucco Aluminium Board",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10068_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/10068_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  31
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11389-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11389_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11389_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11390-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11390_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11390_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11391-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11391_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11391_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  26
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11392-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11392_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11392_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11393-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11393_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11393_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  29
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13830-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13830_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13830_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  2
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13829-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13829_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13829_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "turquoise-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13828-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Turquoise Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13828_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13828_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "white-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11433-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11433_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11433_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  10
    },
    {
        "id":  "white-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11434-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11434_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11434_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "white-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11435-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11435_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11435_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  23
    },
    {
        "id":  "white-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11436-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11436_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11436_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "white-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11437-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11437_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11437_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  32
    },
    {
        "id":  "white-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13833-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13833_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13833_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "white-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13832-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13832_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13832_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  20
    },
    {
        "id":  "white-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13831-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "White Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13831_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13831_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    },
    {
        "id":  "yellow-rigid-pvc-laminate-23-39-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11413-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11413_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11413_0_l.jpg",
        "price_adjustment":  "23.39",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  11
    },
    {
        "id":  "yellow-rigid-pvc-laminate-29-24-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11414-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11414_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11414_0_l.jpg",
        "price_adjustment":  "29.24",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  14
    },
    {
        "id":  "yellow-rigid-pvc-laminate-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11415-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11415_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11415_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  25
    },
    {
        "id":  "yellow-rigid-pvc-laminate-40-94-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11416-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11416_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11416_0_l.jpg",
        "price_adjustment":  "40.94",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  12
    },
    {
        "id":  "yellow-rigid-pvc-laminate-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-11417-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11417_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/11417_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  32
    },
    {
        "id":  "yellow-rigid-pvc-laminate-with-90mm-lid-35-09-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13836-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13836_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13836_0_l.jpg",
        "price_adjustment":  "35.09",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  1
    },
    {
        "id":  "yellow-rigid-pvc-laminate-with-90mm-lid-46-79-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13835-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13835_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13835_0_l.jpg",
        "price_adjustment":  "46.79",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  19
    },
    {
        "id":  "yellow-rigid-pvc-laminate-with-90mm-lid-58-49-https-www-flightcasewarehouse-co-uk-content-shared-productpics-13834-0-l-jpg",
        "option_group":  "Personalise this item with coloured board",
        "color_name":  "Yellow Rigid PVC Laminate With 90mm Lid",
        "color_hex":  "",
        "swatch_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13834_0_l.jpg",
        "option_image_url":  "https://www.flightcasewarehouse.co.uk/content/shared/productpics/13834_0_l.jpg",
        "price_adjustment":  "58.49",
        "default_option":  false,
        "notes":  "Preserve as ACF/custom meta. Do not import as WooCommerce variation.",
        "source_count":  41
    }
] satisfies ColourBoardChoice[];
